# It seems that an exception is installed with app.kubernetes.io/name:  microsoft.flux
# However, the pod templates have changed to app.kubernetes.io/name:  flux-extension
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  namespace: flux-system
resources:
  - flux-pod-identity-exception.yaml
