apiVersion: v1
kind: Namespace
metadata:
  name: "${namespace}"
  labels:
    openservicemesh.io/monitored-by: osm
    toolkit.fluxcd.io/tenant: "${team}"
    colinmac.dev/pci-scope: "${pci-scope}"
    colinmac.dev/team: "${team}"
  annotations:
    openservicemesh.io/sidecar-injection: enabled