apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: core-platform
resources:
  - sources
  - colinmac-tls
  - ingress-nginx
  - keda
  # - haproxy
patches:
  - patch: |
      - op: add
        path: /spec/serviceAccountName
        value: core-platform-developers      
    target:
      kind: HelmRelease
