apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: core-platform
resources:
  - sources
  - colinmac-tls
  - ingress-nginx
  - keda
  # - haproxy
patches:
  - patch: |
      - op: add
        path: /spec/serviceAccountName
        value: core-platform-developers      
    target:
      kind: HelmRelease
  - patch: |
      - op: add
        path: /spec/template/spec/nodeSelector/compliance.colinmac.dev~1pci-scope
        value: out-of-scope
    target:
      kind: Deployment
      labelSelector: "compliance.colinmac.dev/pci-scope=out-of-scope"
  - patch: |
      - op: add
        path: /spec/template/spec/nodeSelector/compliance.colinmac.dev~1pci-scope
        value: in-scope
    target:
      kind: Deployment
      labelSelector: "compliance.colinmac.dev/pci-scope=in-scope"