apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: haproxy-private
spec:
  releaseName: haproxy-private
  chart:
    spec:
      chart: kubernetes-ingress
      sourceRef:
        kind: HelmRepository
        name: haproxytech
        namespace: core-platform
      # version: "" latest
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  # https://github.com/haproxytech/helm-charts/blob/main/kubernetes-ingress/values.yaml
  values:
    controller:
      logging:
        level: debug
      replicaCount: 1
      service:
        type: LoadBalancer
        annotations:
           service.beta.kubernetes.io/azure-load-balancer-internal: "true"
      ingressClass: haproxy-private
      ingressClassResource:
        name: haproxy-private
        default: false
      podLabels:
        aadpodidbinding: cert-provider
      extraVolumes:
          - name: colinmac-tls # TODO: variable
            csi:
              driver: secrets-store.csi.k8s.io
              readOnly: true
              volumeAttributes:
                secretProviderClass: "colinmac-local-tls" # TODO: variable
      extraVolumeMounts:
          - name: colinmac-tls # TODO: variable
            mountPath: "/mnt/secrets-store"
            readOnly: true
      defaultTLSSecret:
        secret: colinmac-local-tls
    defaultBackend: 
      enabled: false