apiVersion: config.openservicemesh.io/v1alpha1
kind: MeshConfig
metadata:
  name: osm-mesh-config
  namespace: kube-system
spec:
  # NOTE: During bootstrapping of a fresh cluster, this ingress won't be deployed. This race condition may cause issues.
  certificate:
    certKeyBitSize: 2048
    serviceCertValidityDuration: 24h
    ingressGateway:
      secret:
        name: osm-private-nginx-client-cert
        namespace: core-platform
      subjectAltNames: 
        - ingress-nginx-private-controller.core-platform.cluster.local
      validityDuration: 240h
  featureFlags:
    enableEgressPolicy: true
    enableWASMStats: true
    enableMulticlusterMode: false
    enableSnapshotCacheMode: false
    enableAsyncProxyServiceMapping: false
    enableIngressBackendPolicy: true
    enableEnvoyActiveHealthChecks: false
    enableRetryPolicy: false
  observability:
    enableDebugServer: false
    osmLogLevel: info
    tracing:
      enable: false
  sidecar:
    enablePrivilegedInitContainer: false
    logLevel: error
    maxDataPlaneConnections: 0
  traffic:
    enableEgress: true
    enablePermissiveTrafficPolicyMode: false
    outboundIPRangeExclusionList:
      - 169.254.169.254/32 # Azure Instance Metadata Service
      - 168.63.129.16/32 # Azure DNS