# TODO: Migrating to kustomization based on cloud deploy https://github.com/kubernetes/ingress-nginx/blob/main/deploy/static/provider/cloud/deploy.yaml
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: ingress-nginx
spec:
  interval: 30m
  url: https://kubernetes.github.io/ingress-nginx
