apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
spec:
  releaseName: grafana
  chart:
    spec:
      chart: grafana
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: core-monitoring
      # version: "" latest
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  # https://github.com/haproxytech/helm-charts/blob/main/kubernetes-ingress/values.yaml
  values:
    labels:
      colinmac.dev/pci-scope: out-of-scope
    podLabels:
      colinmac.dev/pci-scope: out-of-scope
      aadpodidbinding: grafana-operator
    ingress:
      enabled: true
      ingressClassName: nginx-private
      annotations:
        nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
        # proxy_ssl_name for a service is of the form <service-account>.<namespace>.cluster.local
        nginx.ingress.kubernetes.io/configuration-snippet: |
          proxy_ssl_name "grafana.core-platform.cluster.local";
        nginx.ingress.kubernetes.io/proxy-ssl-secret: "core-platform/osm-private-nginx-client-cert"
        nginx.ingress.kubernetes.io/proxy-ssl-verify: "on"
        nginx.ingress.kubernetes.io/rewrite-target: /$1
        nginx.ingress.kubernetes.io/use-regex: "true"

      path: /grafana/?(.*)      
      hosts:
        - monitoring.colinmac.local
      tls:
        - hosts:
          - monitoring.colinmac.local
    extraSecretMounts:
      - name: secrets-store-inline
        mountPath: /run/secret-config
        readOnly: true
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "grafana-config"
    grafana.ini:
      paths:
        data: /var/lib/grafana/
        logs: /var/log/grafana
        plugins: /var/lib/grafana/plugins
        provisioning: /etc/grafana/provisioning
      analytics:
        check_for_updates: true
        # application_insights_connection_string: `GF_AUTH_AZUREAD_CLIENT_ID`
      log:
        mode: console
      grafana_net:
        url: https://grafana.net
      server:
        root_url: monitoring.colinmac.local/grafana
        domain: monitoring.colinmac.local
      security:
        disable_initial_admin_creation: true
      auth:
        disable_login_form: true
      azure:
        managed_identity_enabled: true
        managed_identity_client_id: a6f92948-bf47-4961-89eb-cbd686b94b8a
      # users:
      #   allow_sign_up: false
      #   external_manage_link_url:
      #   external_manage_link_name:
      #   external_manage_info:
      alerting:
        enabled: false # Disables legacy alerting
      auth.generic_oauth:
        name: AD B2C - OinkFinancial
        enabled: true
        allow_sign_up: true
        auth_url: https://oinkfinancial.b2clogin.com/colinmac.dev/oauth2/v2.0/authorize?p=b2c_1a_grafana_signup_signin
        token_url: https://oinkfinancial.b2clogin.com/colinmac.dev/oauth2/v2.0/token?p=b2c_1a_grafana_signup_signin
        api_url: https://oinkfinancial.b2clogin.com/colinmac.dev/openid/v2.0/userinfo?p=b2c_1a_grafana_signup_signin
        use_pkce: true
        role_attribute_strict: false # TODO: switch to true
        role_attribute_path: role
        groups_attribute_path: groups
        team_ids_attribute_path: teams
        # client_id: GF_AUTH_GENERIC_OAUTH_CLIENT_ID
        # client_secret: GF_AUTH_GENERIC_OAUTH_CLIENT_ID
        client_id: $__file{/run/secret-config/grafana-oauth-clientid}
        client_secret: $__file{/run/secret-config/grafana-oauth-clientsecret}
        scopes: openid email profile