apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: grafana-config
spec:
  provider: azure
  # secretObjects:
  # - secretName: grafana-oauth-config
  #   type: Opaque
  #   data: 
  #   - objectName: grafana-oauth-clientsecret
  #     key: clientsecret
  #   - objectName: grafana-oauth-clientid
  #     key: clientid
  parameters:
    usePodIdentity: "true"
    keyvaultName: lz-workloads-config
    objects: |
      array:
        - |
          objectName: grafana-oauth-clientsecret
          objectType: secret
        - |
          objectName: grafana-oauth-clientid
          objectType: secret
    tenantId: 72f988bf-86f1-41af-91ab-2d7cd011db47   