apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: grafana-config
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: grafana
    app.kubernetes.io/version: "8.4.2"
spec:
  provider: azure
  secretObjects:
  - secretName: grafana-storage
    type: Opaque
    data: 
    - objectName: grafana-storage-name
      key: azurestorageaccountname
    - objectName: grafana-storage-key
      key: azurestorageaccountkey
  parameters:
    usePodIdentity: "true"
    keyvaultName: oink-mgmt-monitoring
    objects: |
      array:
        - |
          objectName: grafana-oauth-clientsecret
          objectType: secret
        - |
          objectName: grafana-oauth-clientid
          objectType: secret
        - |
          objectName: grafana-storage-key
          objectType: secret
        - |
          objectName: grafana-storage-name
          objectType: secret
        - |
          objectName: oink-mgmt-monitoring-appinsights-connectionstring
          objectType: secret
          objectAlias: app-insights-connection-string
    tenantId: 72f988bf-86f1-41af-91ab-2d7cd011db47
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: grafana-datasources
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: grafana
    app.kubernetes.io/version: "8.4.2"
spec:
  provider: azure
  parameters:
    usePodIdentity: "true"
    keyvaultName: oink-mgmt-monitoring
    objects: |
      array:
        - |
          objectName: grafana-datasources-default
          objectType: secret
          objectAlias: default.yaml
    tenantId: 72f988bf-86f1-41af-91ab-2d7cd011db47   