apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../_scoped-workload-template
  - cluster-role-binding.yaml
  - network-allowall.yaml
  - resource-quota.yaml
  - sync.yaml
