apiVersion: v1
kind: ResourceQuota
metadata:
  name: default
  namespace: ${namespace}
spec:
  hard:
    # 300m - grafana (+ envoy & sidecars)
    # 250m - jaeger (+ envoy)
    # 550m - Allow for x2 horizontal growth on above
    # 300m - Rolling updates
    requests.cpu: 1400m

    # 300Mi - grafana (+ envoy & sidecars)
    # 250Mi - jaeger (+ envoy)
    # 550Mi - Allow for x2 horizontal growth on above
    # 300Mi - Rolling updates
    requests.memory: 1400Mi
    requests.storage: "0"

    # 400m - grafana (+ envoy & sidecars)
    # 250Mi - jaeger (+ envoy)
    # 650m - Allow for x2 horizontal growth on above
    # 400m - Rolling updates
    limits.cpu: 1700m

    # 600Mi - grafana (+ envoy & sidecars)
    # 350Mi - jaeger (+ envoy)
    # 950Mi - Allow for x2 horizontal growth on above
    # 600Mi - Rolling updates
    limits.memory: 2500Mi
    count/persistentvolumeclaims: "0"

    # 1 - grafana (ClusterIP)
    # 1 - httpbin (ClusterIP)
    # 1 - jaeger (ClusterIP)
    count/services: "3"
    count/services.loadbalancers: "0"
    count/services.nodeports: "0"

    # 1 - grafana
    # 1 - httpbin
    # 1 = jaeger
    count/deployments.apps: "3"
    count/daemonset.apps: "0"

    # 1 - grafana
    # 1 - httpbin
    # 1 = jaeger
    # 2 - Allow for x2 horizontal growth on above
    # 1 - Rolling updates
    count/pods: "6"