apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: ${team}
  namespace: ${namespace}
spec:
  interval: 10m
  url: https://github.com/colincmac/aks-lz-manifests
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: ${team}
  namespace: ${namespace}
spec:
  path: ./core-monitoring
  serviceAccountName: ${team}
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: ${team}
  prune: true
  validation: client

