apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: core-monitoring-config
spec:
  path: ./tenants/_base/core-monitoring-team
  prune: true
  interval: 10m
  serviceAccountName: kustomize-controller
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substitute:
      team: core-monitoring-developers
      namespace: core-monitoring
      pciScope: out-of-scope
      # You would want to separate these roles in real-world scenarios
      adminGroup: a5892987-ce42-4067-be7c-ac40c6ecc3bf
      editorGroup: a5892987-ce42-4067-be7c-ac40c6ecc3bf
      viewerGroup: a5892987-ce42-4067-be7c-ac40c6ecc3bf
      maxContainerCPU: 1000m
      maxContainerMemory: 1000Mi