apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
commonLabels:
  colinmac.dev/env: Production
resources:
  - ./core-monitoring-team.yaml
  - ./core-platform-team.yaml
  - ./shared-services-team.yaml
  - ./oink-financial-accounts-team.yaml
  - ./oink-account-payments-team.yaml