# Eventually we should deploy this without a default identity
# https://github.com/kedacore/keda/issues/2656

apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keda
spec:
  releaseName: keda
  chart:
    spec:
      chart: keda
      sourceRef:
        kind: HelmRepository
        name: keda
        namespace: core-platform
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  # postRenderers:
  #   - kustomize:
  #       patches:
  #         - patch: |
  #             - op: add
  #               path: /spec/template/spec/nodeSelector/compliance.colinmac.dev~1pci-scope
  #               value: out-of-scope
  #           target:
  #             kind: Deployment
  #             labelSelector: "compliance.colinmac.dev/pci-scope=out-of-scope"
  #         - patch: |
  #             - op: add
  #               path: /spec/template/spec/nodeSelector/compliance.colinmac.dev~1pci-scope
  #               value: in-scope
  #           target:
  #             kind: Deployment
  #             labelSelector: "compliance.colinmac.dev/pci-scope=in-scope"  
  # Default values
  # https://github.com/kedacore/charts/blob/main/keda/values.yaml
  values:
    podIdentity:
      activeDirectory:
        identity: keda-operator
    nodeSelector:
        kubernetes.io/os: linux
        compliance.colinmac.dev/pci-scope: out-of-scope