apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: user-mgmt-func
  namespace: prod
spec:
  podIdentity:
    provider: azure

---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: user-mgmt-func
  namespace: prod
spec:
  scaleTargetRef:
    name: durabletask-mssql-user-mgmt # e.g. the name of the resource to scale
  triggers:
  - type: mssql
    metadata:
      targetValue: "1"
      query: "SELECT dt.GetScaleRecommendation(8, 8)" # (@MaxOrchestrationsPerWorker, @MaxActivitiesPerWorker)
    authenticationRef:
      name: user-mgmt-func