apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keda
  namespace: flux-system
spec:
  targetNamespace: core
  releaseName: keda
  chart:
    spec:
      chart: keda
      sourceRef:
        kind: HelmRepository
        name: keda
        namespace: flux-system
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  # Default values
  # https://github.com/kedacore/charts/blob/main/keda/values.yaml
  values:
    podIdentity:
      activeDirectory: keda-operator