apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: colinmac-local-tls
spec:
  provider: azure
  secretObjects:
  - secretName: colinmac-local-tls
    type: kubernetes.io/tls
    data: 
    - objectName: ColinMacLocal-TLS
      key: tls.key
    - objectName: ColinMacLocal-TLS
      key: tls.crt
  parameters:
    usePodIdentity: "true"
    keyvaultName: signing-store-001
    objects: |
      array:
        - |
          objectName: ColinMacLocal-TLS
          objectType: secret
    tenantId: 72f988bf-86f1-41af-91ab-2d7cd011db47   