apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: haproxy-private
  namespace: flux-system
spec:
  releaseName: haproxy-ingress-private
  targetNamespace: core
  chart:
    spec:
      chart: kubernetes-ingress
      sourceRef:
        kind: HelmRepository
        name: haproxytech
        namespace: flux-system
      # version: "" latest
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  # https://github.com/haproxytech/helm-charts/blob/main/kubernetes-ingress/values.yaml
  values:
    controller:
      replicaCount: 1
      service:
        type: LoadBalancer
        annotations:
           service.beta.kubernetes.io/azure-load-balancer-internal: "true"
      ingressClass: haproxy-private
      ingressClassResource:
        name: haproxy-private
        default: false
    defaultBackend: 
      enabled: false