apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: haproxy-public
spec:
  releaseName: haproxy-ingress-public
  chart:
    spec:
      chart: kubernetes-ingress
      sourceRef:
        kind: HelmRepository
        name: haproxytech
        namespace: core
      # version: "" latest
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  # https://github.com/haproxytech/helm-charts/blob/main/kubernetes-ingress/values.yaml
  values:
    controller:
      replicaCount: 1
      service:
        type: LoadBalancer
      ingressClass: haproxy-public
      ingressClassResource:
        name: haproxy-public
        default: false
      podLabels:
        aadpodidbinding: core-certmanager
      extraVolumes:
          - name: colinmac-tls # TODO: variable
            csi:
              driver: secrets-store.csi.k8s.io
              readOnly: true
              volumeAttributes:
                secretProviderClass: "colinmac-dev-tls" # TODO: variable
      extraVolumeMounts:
          - name: colinmac-tls # TODO: variable
            mountPath: "/mnt/secrets-store"
            readOnly: true
    defaultBackend: 
      enabled: false