apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
  labels:
    app.kubernetes.io/instance: flux-system
    app.kubernetes.io/part-of: flux
spec:
  interval: 1m
  ref:
    branch: main
  url: https://github.com/colincmac/aks-lz-manifests

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
  labels:
    app.kubernetes.io/instance: flux-system
    app.kubernetes.io/part-of: flux
spec:
  interval: 10m
  path: ./clusters
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client