apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: contour-private
  namespace: flux-system
spec:
  releaseName: contour-ingress-private
  targetNamespace: core
  chart:
    spec:
      chart: contour
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      # version: "" latest
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  # https://github.com/bitnami/charts/tree/master/bitnami/contour
  values:
    contour:
      manageCRDs: false
      service:
        annotations:
           service.beta.kubernetes.io/azure-load-balancer-internal: "true"
      ingressClass:
        name: 'contour-private'
        default: false