apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: contour-public
  namespace: flux-system
spec:
  releaseName: contour-ingress-public
  targetNamespace: core
  chart:
    spec:
      chart: contour
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      # version: "" latest
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  # https://github.com/bitnami/charts/tree/master/bitnami/contour
  values:
    contour:
      ingressClass:
        name: 'contour-public'
        default: true