apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-private
  namespace: flux-system
spec:
  releaseName: nginx-ingress-private
  targetNamespace: core
  chart:
    spec:
      chart: ingress-nginx
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
      # version: "" latest
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  # https://github.com/kubernetes/ingress-nginx/tree/main/charts/ingress-nginx
  values:
    controller:
      service:
          annotations:
            # Create internal LB
            service.beta.kubernetes.io/azure-load-balancer-internal: "true"
      image:
        allowPrivilegeEscalation: false
      ingressClassResource:
        name: 'nginx-private'
        default: true