apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-public
spec:
  releaseName: nginx-ingress-public
  chart:
    spec:
      chart: ingress-nginx
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: core
      # version: "" latest
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  # https://github.com/kubernetes/ingress-nginx/tree/main/charts/ingress-nginx
  values:
    controller:
      podLabels:
        aadpodidbinding: core-certmanager
      extraVolumes:
          - name: colinmac-tls # TODO: variable
            csi:
              driver: secrets-store.csi.k8s.io
              readOnly: true
              volumeAttributes:
                secretProviderClass: "colinmac-dev-tls" # TODO: variable
      extraVolumeMounts:
          - name: colinmac-tls # TODO: variable
            mountPath: "/mnt/secrets-store"
            readOnly: true
      image:
        allowPrivilegeEscalation: false
      ingressClassResource:
        name: 'nginx-public'
        default: true